### ISSUE TITLE
Разбиваем на папки

### ISSUE THREAD

**Issue by NikAshanin** [votruk/node-pagination#8]
Исходный 1 файл разбиваем на папки routes/models/logic
Работу с бд вынести из роутов соответственно.

Для каждого метода создать отдельный файл роута (уже есть)

И сложить routes/models/logic в message папку (уже есть)

**Comment by votruk** [comment]
> Работу с бд вынести из роутов соответственно.

С учетом того, что класс db.js будет переделан на работу с ормкой, что еще нужно сделать? Чтобы все методы по взаимодействию с базой находились в db.js?

**Comment by NikAshanin** [comment]
да, в logic или model

**Comment by votruk** [comment]
Сделал разбиение
